export const usersList = [
    {
        id: 'u15',
        image: require('../assets/images/users/user15.png'),
        name: 'Amral Willim',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u13',
        image: require('../assets/images/users/user13.png'),
        name: 'Kayra Graive',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u12',
        image: require('../assets/images/users/user12.png'),
        name: 'Diya Patel',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u11',
        image: require('../assets/images/users/user11.png'),
        name: 'Jerry Fransis',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u4',
        image: require('../assets/images/users/user7.png'),
        name: 'John Joh',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u5',
        image: require('../assets/images/users/user6.png'),
        name: 'Merry Johnson',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u6',
        image: require('../assets/images/users/user5.png'),
        name: 'Samantha Smith',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u7',
        image: require('../assets/images/users/user4.png'),
        name: 'Rita Grove',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u8',
        image: require('../assets/images/users/user3.png'),
        name: 'Perry Johnson',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u9',
        image: require('../assets/images/users/user2.png'),
        name: 'Johnson Singa',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u10',
        image: require('../assets/images/users/user1.png'),
        name: 'Curry Ton',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u3',
        image: require('../assets/images/users/user14.png'),
        name: 'Perry Johnson',
        age: 25,
        profession: 'Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u2',
        image: require('../assets/images/users/user8.png'),
        name: 'Robot Robinson',
        age: 25,
        profession: 'Software Developer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
    {
        id: 'u1',
        image: require('../assets/images/users/user10.png'),
        name: 'Annie Robinson',
        age: 25,
        profession: 'Junior Software Engineer',
        isFavorite: false,
        address: 'Ievine',
        distance: '3.2km',
    },
]